import { readFile, readdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import type { Plugin } from 'vite';
import { defineConfig } from 'vite';
import type { LevelData } from '../shared/types';
import { TILES_X, TILES_Y } from '../shared/types';

const LEVELS_DIR = fileURLToPath(new URL('./src/levels/', import.meta.url));
const LEVELS_INDEX = `${LEVELS_DIR}index.ts`;
/** The id is the file name. Nothing outside this alphabet ever touches a path. */
const SLUG = /^[a-z0-9-]+$/;
const IMPORT_END = '// designer:imports:end';
const LEVELS_END = '// designer:levels:end';

/** Level id → the identifier its import is bound to in the registry. */
const identOf = (id: string): string => `LEVEL_${id.replace(/-/g, '_')}`;

/**
 * What the designer is allowed to save. Everything past this point writes to
 * the repo, so the checks are structural rather than advisory: a bad map is a
 * floor the selftest would reject at build time, and a bad id is a path.
 */
function invalidLevel(level: LevelData | undefined): string | null {
  if (!level || typeof level !== 'object') return 'body has no level';
  const meta = level.meta;
  if (!meta || typeof meta.id !== 'string' || !SLUG.test(meta.id)) {
    return 'meta.id must be a slug [a-z0-9-]';
  }
  if (typeof meta.name !== 'string' || meta.name.length === 0) return 'meta.name is required';
  if (typeof meta.order !== 'number' || !Number.isFinite(meta.order)) {
    return 'meta.order must be a number';
  }
  if (!Array.isArray(level.map) || level.map.length !== TILES_Y) {
    return `map must have exactly ${TILES_Y} rows`;
  }
  for (const [y, row] of level.map.entries()) {
    if (typeof row !== 'string' || row.length !== TILES_X) {
      return `map row ${y} must be exactly ${TILES_X} characters`;
    }
  }
  for (const key of ['entities', 'triggers', 'sounds'] as const) {
    if (!Array.isArray(level[key])) return `${key} must be an array`;
  }
  return null;
}

/** Add the import + array entry for `id` if the registry has not got them. */
function upsertRegistry(source: string, id: string): string {
  const ident = identOf(id);
  let out = source;
  const importLine = `import { LEVEL as ${ident} } from './${id}.level';`;
  if (!out.includes(importLine)) out = out.replace(IMPORT_END, `${importLine}\n${IMPORT_END}`);
  // The marker keeps its own indentation, so the entry is inserted bare.
  if (!new RegExp(`^\\s*${ident},\\s*$`, 'm').test(out)) {
    out = out.replace(LEVELS_END, `${ident},\n  ${LEVELS_END}`);
  }
  return out;
}

function levelSource(level: LevelData): string {
  return `/**
 * GENERATED by the level designer (/designer.html). Edit it there and save —
 * a hand edit here survives, but the designer overwrites the whole file.
 */
import type { LevelData } from '../../../shared/types';

export const LEVEL: LevelData = ${JSON.stringify(level, null, 2)};
`;
}

/**
 * The level designer's save endpoint. `apply: 'serve'` ONLY: this writes source
 * files, and the shipping bundle must contain nothing that can (rule 1).
 */
function designerSave(): Plugin {
  return {
    name: 'robot-operator-designer-save',
    apply: 'serve',
    configureServer(server) {
      server.middlewares.use('/__designer/levels', (_req, res) => {
        void readdir(LEVELS_DIR)
          .then((names) => names.filter((n) => n.endsWith('.level.ts')).map((n) => n.slice(0, -9)))
          .catch(() => [] as string[])
          .then((ids) => {
            res.setHeader('content-type', 'application/json');
            res.end(JSON.stringify({ ids }));
          });
      });

      server.middlewares.use('/__designer/save', (req, res) => {
        const fail = (code: number, error: string): void => {
          res.statusCode = code;
          res.setHeader('content-type', 'application/json');
          res.end(JSON.stringify({ error }));
        };
        if (req.method !== 'POST') return fail(405, 'POST only');
        const chunks: Buffer[] = [];
        req.on('data', (c: Buffer) => chunks.push(c));
        req.on('end', () => {
          let level: LevelData | undefined;
          try {
            level = (JSON.parse(Buffer.concat(chunks).toString('utf8')) as { level?: LevelData })
              .level;
          } catch {
            return fail(400, 'body is not JSON');
          }
          const bad = invalidLevel(level);
          if (bad || !level) return fail(400, bad ?? 'invalid level');
          const id = level.meta.id;
          void (async () => {
            try {
              await writeFile(`${LEVELS_DIR}${id}.level.ts`, levelSource(level), 'utf8');
              const index = await readFile(LEVELS_INDEX, 'utf8');
              const next = upsertRegistry(index, id);
              if (next !== index) await writeFile(LEVELS_INDEX, next, 'utf8');
              res.setHeader('content-type', 'application/json');
              res.end(JSON.stringify({ ok: true, id }));
            } catch (err) {
              fail(500, err instanceof Error ? err.message : String(err));
            }
          })();
        });
      });
    },
  };
}

// Self-contained bundle law: relative base, no runtime CDN, everything bundled.
export default defineConfig({
  base: './',
  plugins: [designerSave()],
  resolve: {
    alias: {
      '@shared': fileURLToPath(new URL('../shared', import.meta.url)),
    },
  },
  server: {
    port: 5173,
    proxy: {
      '/api': 'http://localhost:8790',
    },
  },
  build: {
    target: 'es2022',
    assetsInlineLimit: 0,
    rollupOptions: {
      // lab.html and designer.html are the other two entries: the graphics lab
      // (src/lab/) and the level designer (src/designer/). Both ship with the
      // build so they can be opened from the deployed URL, and both cost the
      // game nothing — nothing in src/ imports either. The designer's Save
      // button hides itself when `/__designer/save` is not there to answer,
      // which is exactly the case in a built bundle.
      input: {
        main: fileURLToPath(new URL('./index.html', import.meta.url)),
        lab: fileURLToPath(new URL('./lab.html', import.meta.url)),
        designer: fileURLToPath(new URL('./designer.html', import.meta.url)),
      },
    },
  },
});
