/**
 * GENERATED by the level designer (/designer.html). Edit it there and save —
 * a hand edit here survives, but the designer overwrites the whole file.
 */
import type { LevelData } from '../../../shared/types';

export const LEVEL: LevelData = {
  "meta": {
    "id": "floor-1-copy",
    "name": "FLOOR 1 COPY",
    "order": 0,
    "replaces": 1,
    "seed": 66029
  },
  "map": [
    "##############################",
    "#............................#",
    "#...####..............####...#",
    "#...####..............####...#",
    "#............................#",
    "#............................#",
    "#............................#",
    "#............................#",
    "#............................#",
    "#............................#",
    "#............................#",
    "#...####..............####...#",
    "#...####..............####...#",
    "#............................#",
    "#............................#",
    "##############################"
  ],
  "entities": [
    {
      "id": "elevB",
      "kind": "elevatorB",
      "tx": 15,
      "ty": 3,
      "label": "elevator"
    },
    {
      "id": "pile1",
      "kind": "debris",
      "tx": 15,
      "ty": 8,
      "label": "pile of broken machines"
    },
    {
      "id": "scrap1",
      "kind": "scrap",
      "tx": 24,
      "ty": 5,
      "label": "scrap"
    },
    {
      "id": "scrap2",
      "kind": "scrap",
      "tx": 7,
      "ty": 6,
      "label": "scrap"
    },
    {
      "id": "chair1",
      "kind": "chair",
      "tx": 11,
      "ty": 6,
      "label": "office chair",
      "hp": 1
    },
    {
      "id": "pile3",
      "kind": "debris",
      "tx": 10,
      "ty": 12,
      "label": "pile of broken machines"
    },
    {
      "id": "pile5",
      "kind": "debris",
      "tx": 19,
      "ty": 10,
      "label": "pile of broken machines"
    },
    {
      "id": "pile6",
      "kind": "debris",
      "tx": 28,
      "ty": 8,
      "label": "pile of broken machines"
    },
    {
      "id": "pile7",
      "kind": "debris",
      "tx": 28,
      "ty": 14,
      "label": "pile of broken machines"
    },
    {
      "id": "pile8",
      "kind": "debris",
      "tx": 2,
      "ty": 7,
      "label": "pile of broken machines"
    }
  ],
  "triggers": [],
  "sounds": [],
  "spawn": {
    "tx": 15,
    "ty": 8
  },
  "decor": [
    {
      "id": "sconce_body",
      "name": "wall_lamp",
      "tx": 4.5,
      "ty": 3.62,
      "ceiling": true,
      "fixtureKind": "wall",
      "fixtureId": "sconce"
    },
    {
      "id": "sconce2_body",
      "name": "wall_lamp",
      "tx": 22.5,
      "ty": 3.62,
      "ceiling": true,
      "fixtureKind": "wall",
      "fixtureId": "sconce2"
    },
    {
      "id": "sconce3_body",
      "name": "wall_lamp",
      "tx": 25.5,
      "ty": 3.62,
      "ceiling": true,
      "fixtureKind": "wall",
      "fixtureId": "sconce3"
    },
    {
      "id": "sconce4_body",
      "name": "wall_lamp",
      "tx": 4.5,
      "ty": 12.62,
      "ceiling": true,
      "fixtureKind": "wall",
      "fixtureId": "sconce4"
    },
    {
      "id": "sconce5_body",
      "name": "wall_lamp",
      "tx": 7.5,
      "ty": 12.62,
      "ceiling": true,
      "fixtureKind": "wall",
      "fixtureId": "sconce5"
    },
    {
      "id": "sconce6_body",
      "name": "wall_lamp",
      "tx": 22.5,
      "ty": 12.62,
      "ceiling": true,
      "fixtureKind": "wall",
      "fixtureId": "sconce6"
    },
    {
      "id": "sconce7_body",
      "name": "wall_lamp",
      "tx": 25.5,
      "ty": 12.62,
      "ceiling": true,
      "fixtureKind": "wall",
      "fixtureId": "sconce7"
    },
    {
      "id": "sconce8_body",
      "name": "wall_lamp",
      "tx": 6.5,
      "ty": 3.62,
      "ceiling": true,
      "fixtureKind": "wall",
      "fixtureId": "sconce8"
    },
    {
      "id": "tube3_body",
      "name": "ceiling_lamp",
      "tx": 23.75,
      "ty": 8.75,
      "ceiling": true,
      "fixtureId": "tube3",
      "fixtureKind": "ceiling"
    },
    {
      "id": "sparks_box",
      "name": "sparks_box",
      "tx": 10.75,
      "ty": 8.75,
      "foot": [
        10,
        5
      ],
      "reflect": true
    },
    {
      "id": "sparks_box2",
      "name": "sparks_box",
      "tx": 18.75,
      "ty": 11,
      "foot": [
        10,
        5
      ],
      "reflect": true
    },
    {
      "id": "desk3",
      "name": "desk",
      "tx": 9.75,
      "ty": 5.25,
      "foot": [
        24,
        10
      ],
      "reflect": true
    },
    {
      "id": "trolley",
      "name": "trolley",
      "tx": 11.75,
      "ty": 10.75,
      "foot": [
        18,
        6
      ],
      "reflect": true
    },
    {
      "id": "plant_dead",
      "name": "plant_dead",
      "tx": 5.25,
      "ty": 4.75,
      "foot": [
        10,
        6
      ],
      "reflect": true
    },
    {
      "id": "plant_dead2",
      "name": "plant_dead",
      "tx": 7.75,
      "ty": 4.5,
      "foot": [
        10,
        6
      ],
      "reflect": true
    },
    {
      "id": "plant_dead3",
      "name": "plant_dead",
      "tx": 6.75,
      "ty": 13.5,
      "foot": [
        10,
        6
      ],
      "reflect": true
    },
    {
      "id": "plant_dead4",
      "name": "plant_dead",
      "tx": 24.25,
      "ty": 13.25,
      "foot": [
        10,
        6
      ],
      "reflect": true
    },
    {
      "id": "exit_sign",
      "name": "exit_sign",
      "tx": 15.5,
      "ty": 2.14,
      "ceiling": true,
      "reflect": true
    },
    {
      "id": "puddle",
      "name": "puddle",
      "tx": 13,
      "ty": 4.5,
      "reflect": true
    },
    {
      "id": "tube4_body",
      "name": "ceiling_lamp",
      "tx": 6.5,
      "ty": 8.5,
      "ceiling": true,
      "fixtureId": "tube4",
      "fixtureKind": "ceiling"
    },
    {
      "id": "boxes",
      "name": "boxes",
      "tx": 14.25,
      "ty": 8.5,
      "foot": [
        16,
        8
      ],
      "reflect": true
    },
    {
      "id": "cable_coil",
      "name": "cable_coil",
      "tx": 16.75,
      "ty": 8.5
    },
    {
      "id": "cable_coil2",
      "name": "cable_coil",
      "tx": 17.75,
      "ty": 8.5
    },
    {
      "id": "cable_coil4",
      "name": "cable_coil",
      "tx": 18.25,
      "ty": 8.75
    },
    {
      "id": "cable_coil7",
      "name": "cable_coil",
      "tx": 19,
      "ty": 9
    },
    {
      "id": "cable_coil8",
      "name": "cable_coil",
      "tx": 19.5,
      "ty": 9.25
    },
    {
      "id": "cable_coil3",
      "name": "cable_coil",
      "tx": 19.5,
      "ty": 9.75
    }
  ],
  "lights": [
    {
      "id": "tube",
      "tx": 15.5,
      "ty": 8.25,
      "radius": 206,
      "color": 16304283,
      "intensity": 1.69,
      "castShadow": true,
      "kind": "point",
      "dir": 1.5707963267948966,
      "spread": 0.75,
      "flickerHz": 7
    },
    {
      "id": "tube2",
      "tx": 15,
      "ty": 2.18,
      "radius": 96,
      "color": 16758644,
      "intensity": 1.2,
      "castShadow": true
    },
    {
      "id": "sconce",
      "tx": 4.5,
      "ty": 3.62,
      "radius": 62,
      "color": 16758644,
      "intensity": 0.5,
      "kind": "cone",
      "dir": 1.5707963267948966,
      "spread": 0.85,
      "castShadow": false
    },
    {
      "id": "sconce_pt",
      "tx": 4.5,
      "ty": 3.62,
      "radius": 48,
      "color": 16758644,
      "intensity": 0.55,
      "castShadow": false,
      "volumetric": false
    },
    {
      "id": "sconce2",
      "tx": 22.5,
      "ty": 3.62,
      "radius": 62,
      "color": 16758644,
      "intensity": 0.5,
      "kind": "cone",
      "dir": 1.5707963267948966,
      "spread": 0.85,
      "castShadow": false
    },
    {
      "id": "sconce2_pt",
      "tx": 22.5,
      "ty": 3.62,
      "radius": 48,
      "color": 16758644,
      "intensity": 0.55,
      "castShadow": false,
      "volumetric": false
    },
    {
      "id": "sconce3",
      "tx": 25.5,
      "ty": 3.62,
      "radius": 62,
      "color": 16758644,
      "intensity": 0.5,
      "kind": "cone",
      "dir": 1.5707963267948966,
      "spread": 0.85,
      "castShadow": false
    },
    {
      "id": "sconce3_pt",
      "tx": 25.5,
      "ty": 3.62,
      "radius": 48,
      "color": 16758644,
      "intensity": 0.55,
      "castShadow": false,
      "volumetric": false
    },
    {
      "id": "sconce4",
      "tx": 4.5,
      "ty": 12.62,
      "radius": 62,
      "color": 16758644,
      "intensity": 0.5,
      "kind": "cone",
      "dir": 1.5707963267948966,
      "spread": 0.85,
      "castShadow": false
    },
    {
      "id": "sconce4_pt",
      "tx": 4.5,
      "ty": 12.62,
      "radius": 48,
      "color": 16758644,
      "intensity": 0.55,
      "castShadow": false,
      "volumetric": false
    },
    {
      "id": "sconce5",
      "tx": 7.5,
      "ty": 12.62,
      "radius": 37,
      "color": 16758644,
      "intensity": 0.12,
      "kind": "cone",
      "dir": 1.5707963267948966,
      "spread": 0.85,
      "castShadow": false,
      "flicker": 0.65
    },
    {
      "id": "sconce5_pt",
      "tx": 7.5,
      "ty": 12.62,
      "radius": 48,
      "color": 16758644,
      "intensity": 0.55,
      "castShadow": false,
      "volumetric": false
    },
    {
      "id": "sconce6",
      "tx": 22.5,
      "ty": 12.62,
      "radius": 62,
      "color": 16758644,
      "intensity": 0.5,
      "kind": "cone",
      "dir": 1.5707963267948966,
      "spread": 0.85,
      "castShadow": false,
      "flicker": 0.55
    },
    {
      "id": "sconce6_pt",
      "tx": 22.5,
      "ty": 12.62,
      "radius": 48,
      "color": 16758644,
      "intensity": 0.55,
      "castShadow": false,
      "volumetric": false
    },
    {
      "id": "sconce7",
      "tx": 25.5,
      "ty": 12.62,
      "radius": 62,
      "color": 16758644,
      "intensity": 0.27,
      "kind": "cone",
      "dir": 1.5707963267948966,
      "spread": 0.85,
      "castShadow": false,
      "flicker": 0.8
    },
    {
      "id": "sconce7_pt",
      "tx": 25.5,
      "ty": 12.62,
      "radius": 48,
      "color": 16758644,
      "intensity": 0.55,
      "castShadow": false,
      "volumetric": false
    },
    {
      "id": "sconce8",
      "tx": 6.5,
      "ty": 3.62,
      "radius": 62,
      "color": 16758644,
      "intensity": 0.5,
      "kind": "cone",
      "dir": 1.5707963267948966,
      "spread": 0.85,
      "castShadow": false
    },
    {
      "id": "sconce8_pt",
      "tx": 6.5,
      "ty": 3.62,
      "radius": 48,
      "color": 16758644,
      "intensity": 0.55,
      "castShadow": false,
      "volumetric": false
    },
    {
      "id": "tube3",
      "tx": 23.75,
      "ty": 8.75,
      "radius": 150,
      "color": 16758644,
      "intensity": 1.2,
      "castShadow": true
    },
    {
      "id": "tube4",
      "tx": 6.5,
      "ty": 8.5,
      "radius": 150,
      "color": 16758644,
      "intensity": 1.2,
      "castShadow": true
    }
  ],
  "fixtures": [
    {
      "id": "sconce",
      "kind": "wall",
      "style": "sconce",
      "scale": 1,
      "bodyAlpha": 1,
      "glow": 1,
      "mountY": 0,
      "lightX": 0,
      "lightY": 0,
      "spill": 1
    },
    {
      "id": "sconce2",
      "kind": "wall",
      "style": "sconce",
      "scale": 1,
      "bodyAlpha": 1,
      "glow": 1,
      "mountY": 0,
      "lightX": 0,
      "lightY": 0,
      "spill": 1
    },
    {
      "id": "sconce3",
      "kind": "wall",
      "style": "sconce",
      "scale": 1,
      "bodyAlpha": 1,
      "glow": 1,
      "mountY": 0,
      "lightX": 0,
      "lightY": 0,
      "spill": 1
    },
    {
      "id": "sconce4",
      "kind": "wall",
      "style": "sconce",
      "scale": 1,
      "bodyAlpha": 1,
      "glow": 1,
      "mountY": 0,
      "lightX": 0,
      "lightY": 0,
      "spill": 1
    },
    {
      "id": "sconce5",
      "kind": "wall",
      "style": "sconce",
      "scale": 1,
      "bodyAlpha": 1,
      "glow": 1,
      "mountY": 0,
      "lightX": 0,
      "lightY": 0,
      "spill": 1
    },
    {
      "id": "sconce6",
      "kind": "wall",
      "style": "sconce",
      "scale": 1,
      "bodyAlpha": 1,
      "glow": 1,
      "mountY": 0,
      "lightX": 0,
      "lightY": 0,
      "spill": 1
    },
    {
      "id": "sconce7",
      "kind": "wall",
      "style": "sconce",
      "scale": 1,
      "bodyAlpha": 1,
      "glow": 1,
      "mountY": 0,
      "lightX": 0,
      "lightY": 0,
      "spill": 1
    },
    {
      "id": "sconce8",
      "kind": "wall",
      "style": "sconce",
      "scale": 1,
      "bodyAlpha": 1,
      "glow": 1,
      "mountY": 0,
      "lightX": 0,
      "lightY": 0,
      "spill": 1
    },
    {
      "id": "tube3",
      "kind": "ceiling",
      "style": "tube",
      "scale": 1,
      "bodyAlpha": 1,
      "glow": 1
    },
    {
      "id": "tube4",
      "kind": "ceiling",
      "style": "tube",
      "scale": 1,
      "bodyAlpha": 1,
      "glow": 1
    }
  ],
  "look": {
    "ambientLevel": 0.31,
    "ambientColor": 4276048,
    "fogColor": 4343634,
    "fogAmount": 0.27,
    "lightGain": 1.4,
    "lightRadiusScale": 0.69,
    "lightFalloff": 2.3,
    "exposure": 1.17,
    "contrast": 1.24,
    "saturation": 1.27,
    "liftAmount": 0.15,
    "gainAmount": 0.21
  }
};
